.sqlx/query-d3301497a1f07f9ba0876547039b6d64b1d0ad1b6e69e3b0c49bddd462bf061d.json, migrations/20241029130636_username_search.sql, src/routes/api/v1/mod.rs, src/routes/api/v1/search.rs
spec: https://www.notion.so/worldcoin/World-App-Usernames-fff8614bdf8c80628750f1b3394eb5b3?pvs=4#12e8614bdf8c803f8e34f9f8097e1e44
trigram search is interesting, recommend looking it up
=> username search

src/routes/api/v1/register_username.rs, src/routes/api/v1/rename.rs, src/routes/api/v1/update_record.rs, src/types/error.rs
=> Reduce not found noisy logs

src/routes/api/v1/ens_gateway.rs, src/routes/api/v1/mod.rs
https://eips.ethereum.org/EIPS/eip-3668#gateway-interface
=> fix: get endpoint in accordance with ccip spec

src/routes/api/v1/search.rs
=> correction

.sqlx/query-2d645ac54be263c577107c50eb134fdeff39cff96d1779fa016242fb9f41ad49.json, README.md
=> Update SQLX Queries

.sqlx/query-663cbe74585dd067af6802f0c8dad327440ad57bd4933d600efe53a92089cecf.json, .sqlx/query-7a2a60285157478dd7c9feea43f97d7c29d8ce1d21375007bdccc42f18971c78.json
A few more queries were out of date. Build was failing
=> More SQLX Update

src/config.rs
Max connection default is 10. This is causing issues so we are bumping
=> create max connections

src/config.rs
=> switch connection

.github/workflows/pull_request_template.md
=> Require templates for PRS

src/config.rs, src/routes/api/v1/query_multiple.rs
many many many errors, this limit needs more evaluation
=> fix: remove the address limit

.sqlx/query-d980a3d7872c7806ea62fc344b9b6d04ed782d51e8b4c48fda0b9c338022a7af.json
ran `cargo sqlx prepare` bc docker build failed
=> fix: sqlx generated files

.sqlx/query-4bee24c848daf31e3a2a98eff1474b20d9795097de065041652d8883f1083105.json
=> fix: update sqlx

.sqlx/query-7222d43708bd418dfea7103d5d8951bad9eab48ba4d4629729127093f622720d.json
Runned `cargo sqlx prepare` to codegen PG query.
=> Run SQLX prepare

src/data_deletion_worker/deletion_completion_queue.rs, src/data_deletion_worker/deletion_request_queue.rs, src/data_deletion_worker/username_deletion_service.rs, src/data_deletion_worker/worker.rs
=> Add instrumentation to deletion worker

src/data_deletion_worker/deletion_completion_queue.rs, src/main.rs
This PR:
- Fixes SQS issue with completion queue
- Adds error handling to worker initialization
=> Fix SQS issue and add worker initialization error handling

src/data_deletion_worker/deletion_request_queue.rs, src/main.rs
This PR:
- Adds better logging to monitor SQS parsing failures
- Updated log level to `warn`
=> Update SQS parsing logging

src/data_deletion_worker/deletion_request_queue.rs
This PR discards unknown deletion messages, accepting only `user_deletion` and `data_deletion` types.
=> Discard unknown deletion messages

src/data_deletion_worker/username_deletion_service.rs
=> Convert wallet address to checksum

src/data_deletion_worker/username_deletion_service.rs
=> Delete old username entry in deletion requests

src/routes/api/v1/avatar.rs, src/routes/api/v1/query_single.rs
Reduces the caching for DB queries to 1 day instead of 1 week.
=> fix: Reduce caching to 1 day

migrations/20250422215826_fill_minimized_profile_picture.sql
Reverts worldcoin/wld-usernames#100
=> Revert "feat: Fill missing minimized profile picture URL values"

src/verify.rs
Adds logging of the response status and body when an unexpected response is received in the `verify` call.
=> fix: Improve verify calls error logging

src/blocklist.rs
=> compare lowercase
